### ISSUE TITLE
about driver that dragon uesd

### ISSUE THREAD

**Issue by weishuo2** [pakmarkthub/dragon#3]
Hi Dr. Pak Markthub,

Hope this email finds you well. This is Wei Rang, a CS student from Huazhong University of Science and Technology.

Recently I am trying to reproduce your work in DRAGON: Breaking GPU Memory Capacity Limits with Direct NVM Access.

But I can only find the file  NVIDIA-Linux-x86_64-384.81.deb，but not the .run file on NVIDIA official website.

Could you please provide a corresponding .run file or a corresponding download link?

Thank you very much and looking forward to hearing from you.

**Comment by pakmarkthub** [comment]
Hi @weishuo2,

I assume that you use P100 or V100. You can download the .run file from here: https://www.nvidia.com/download/driverResults.aspx/124722/en-us. 

If your GPU is not Tesla class, you may want to search for the appropriate driver from https://www.nvidia.com/Download/Find.aspx?lang=en-us. I am not sure if NVIDIA has the version you are looking for for other classes or not.
