### ISSUE TITLE
Some issues about dragon

### ISSUE THREAD

**Issue by weishuo2** [pakmarkthub/dragon#4]
When I try to run the following command：
../scripts/prepare-dragon-driver nvidia-uvm-<version>.patch NVIDIA-Linux-x86_64-<version>

I encountered some problems，as shown in the screenshot.And I can't find the declaration of the variable in all the given files.
Could you give me some suggestions？Thank you very much and looking forward to hearing from you.
![image](https://user-images.githubusercontent.com/27938020/70103899-53bc7380-1677-11ea-8872-4dad3d264521.png)
![image](https://user-images.githubusercontent.com/27938020/70103919-69319d80-1677-11ea-8115-1ff7c780c682.png)
![image](https://user-images.githubusercontent.com/27938020/70103925-6f277e80-1677-11ea-83f5-1ba00997b054.png)

**Comment by pakmarkthub** [comment]
Can you give me the output from `uname -a`?

**Comment by weishuo2** [comment]
weisuo@mic:~/dragon/drivers$ uname -a
Linux mic 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 上午9:27
收件人:&nbsp;"pakmarkthub/dragon"<dragon@noreply.github.com&gt;;
抄送:&nbsp;"魏硕"<2411602273@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pakmarkthub/dragon] Some issues about dragon (#4)




Can you give me the output from uname -a?

**Comment by weishuo2** [comment]
weisuo@mic:~/dragon/drivers$ uname -a
Linux mic 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pakmarkthub** [comment]
DRAGON needs Linux kernel version 3.10 or above but below 4.0. There are some changes in data structures and APIs from 3.x to 4.x in Linux kernel. The compilation errors come from that.
