### ISSUE TITLE
Writes using Dragon crashes the system for all provided application

### ISSUE THREAD

**Issue by msharmavikram** [pakmarkthub/dragon#6]
@pakmarkthub  We are trying to bring up the Dragon and it's examples. We observe the read-only workloads in dragon work as expected. However, when we do the write to the dragon_map'ed filed, the system crashes without any error message (basically hung).  

It turns out when the program exists (when memory gets freed or inside dragon_unmap call), the system crash occurs. To figure this out, we created a [toy example](https://gist.github.com/msharmavikram/24a59be830c51e6208aeaa51a075cd30#file-dragon_test-cu), where we dragon_map the file with D_F_WRITE | D_F_CREATE flags and call CUDA thread to write 1 to the mapped file using tid 0. We observed the CUDA kernel completing successfully however, the file is not written (the file is created and the contents inside the file is all zeros).  

To understand what is going wrong, we added some print statements inside the dragon_unmap() call. We notice when `cudaFree(addr)`  is called the system crashes. We disabled `cudaFree()` call to see if it works, but the system still crashed when the program exited (and file was not synced with the write data and the created file was all zeroes). So there is something going wrong when memory is freed and we are unable to figure it out. Any pointers on what might be going wrong would be helpful. 

Machine details:
1. Intel Xeon with V100 GPU
2. Kernel 5.3.1 
3. NVIDIA Driver: 440.33.01 with dragon patches

**Comment by pakmarkthub** [comment]
Thank you for reporting this issue. Can I ask you to provide the `dmesg` log from when the kernel panic happens?

If you are not familiar with `dmesg` debugging, please follow the steps below:
1. Open a new terminal session (preferably `ssh` from a different computer) before reproducing the issue.
2. On that session, enter `dmesg -w`. After the command finishes printing the log, it will keep waiting (not terminated). Everything from that point is important and I would like you to report it in this issue.
3. Open a new terminal session and reproduce the bug.
4. Go back to the `dmesg` session, you should see some error messages. Please paste the log here.

**Comment by msharmavikram** [comment]
@pakmarkthub this is not kernel panic. This is system crash (system not responding to any prompt or input. require hard reset). there is no output in the dmesg. The last message is this - 

```
Sep 8 21:33] nvidia-uvm: Loaded the UVM driver, major device number 236.
[  +2.177476] nvidia-uvm: Unloaded the UVM driver.
[  +0.026217] nvidia-uvm: Loaded the UVM driver, major device number 236.
[  +0.749790] nvidia-uvm: Unloaded the UVM driver.
[  +0.025087] nvidia-uvm: Loaded the UVM driver, major device number 236.
[  +0.511925] nvidia-uvm: Unloaded the UVM driver.
[  +0.024086] nvidia-uvm: Loaded the UVM driver, major device number 236.
[  +0.693915] nvidia-uvm: Unloaded the UVM driver.
[  +0.025956] nvidia-uvm: Loaded the UVM driver, major device number 236.

```

(FYI. We tested the writes - in 2 different systems with different configurations and both resulted in the same issue. )

**Comment by msharmavikram** [comment]
Is there a log enable or something that I can use to add an additional debug message that can help here? Let me know and I can do that.

**Comment by pakmarkthub** [comment]
Did you reproduce this issue via `ssh`? Do you have access to the physical console (through PMI is also OK)? Your system might freeze before it could report anything to you via `ssh`, but the physical console should still print out something -- I didn't suggest this route before because it is harder to copy the log out.

**Comment by msharmavikram** [comment]
I have access to IPMI/BMC and even there the story remains the same. There is no additional message popped up. :( 

I added some debug message to the NVIDIA driver code (file: `uvm8_nvgpu.h` at `uvm_nvmgpu_write_begin` function):
The message where it crashed is inside the for loop in the `uvm_nvmgpu_write_begin`  function. 

```
[Sep 8 22:00] nvidia-uvm: Loaded the UVM driver, major device number 235.
[Sep 8 22:03] [Debug] Write begin called
[  +0.000018] [Debug] before struct page
[  +0.000010] [Debug] inode lock captured
[  +0.000012] [Debug] file remove privs
[  +0.000013] [Debug] file update time
               [Debug] Starting Writes
[  +0.000028] [Debug] Writing pageid 0
```

**Comment by msharmavikram** [comment]
The modified `uvm_nvmgpu_write_begin` function call with some basic debug messages added:
```
NV_STATUS uvm_nvmgpu_write_begin(uvm_va_block_t *va_block, bool is_flush)
{
    printk(KERN_INFO "[Debug] Write begin called\n");

    NV_STATUS status = NV_OK;

    int page_id;
    uvm_nvmgpu_range_tree_node_t *nvmgpu_rtn = &va_block->va_range->node.nvmgpu_rtn;

    // Calculate the file offset based on the block start address.
    loff_t file_start_offset = va_block->start - va_block->va_range->node.start;
    loff_t file_position;

    struct file *nvmgpu_file = nvmgpu_rtn->filp;
    struct inode *f_inode = file_inode(nvmgpu_file);
    struct address_space *mapping = nvmgpu_file->f_mapping;
    struct inode *m_inode = mapping->host;
    const struct address_space_operations *a_ops = mapping->a_ops;

    printk(KERN_INFO "[Debug] before struct page\n");

    struct page *page;
    void *fsdata;

    uvm_va_space_t *va_space;

    UVM_ASSERT(va_block->va_range);
    UVM_ASSERT(va_block->va_range->va_space);
    va_space = va_block->va_range->va_space;

    inode_lock(f_inode);

    printk(KERN_INFO "[Debug] inode lock captured\n");

    current->backing_dev_info = inode_to_bdi(m_inode);

    file_remove_privs(nvmgpu_file);

    printk(KERN_INFO "[Debug] file remove privs\n");

    file_update_time(nvmgpu_file);

    printk(KERN_INFO "[Debug] file update time\n [Debug] Starting Writes\n");

    for (page_id = 0; page_id < PAGES_PER_UVM_VA_BLOCK; ++page_id) {
        uvm_gpu_id_t id;
        long f_status = 0;

        printk(KERN_INFO "[Debug] Writing pageid %d\n", page_id);

        file_position = file_start_offset + page_id * PAGE_SIZE;

        if (file_position >= nvmgpu_rtn->size)
            break;

        f_status = a_ops->write_begin(
            nvmgpu_file, 
            mapping, 
            file_position, 
            MIN(PAGE_SIZE, nvmgpu_rtn->size - file_position), 
            0, 
            &page, 
            &fsdata
        );
        
        if (f_status != 0 || page == NULL)
            continue;

        if (mapping_writably_mapped(mapping))
            flush_dcache_page(page);

        fsdata_array[page_id] = fsdata;

        if (va_block->cpu.pages[page_id] != NULL)
            uvm_nvmgpu_unmap_page(va_block, page_id);

        for_each_gpu_id(id) {
            uvm_gpu_t *gpu;
            uvm_va_block_gpu_state_t *gpu_state = va_block->gpus[uvm_id_gpu_index(id)];
            if (!gpu_state)
                continue;

            UVM_ASSERT(gpu_state->cpu_pages_dma_addrs[page_id] == 0);

            gpu = uvm_va_space_get_gpu(va_space, id);

            status = uvm_gpu_map_cpu_pages(gpu, page, PAGE_SIZE, &gpu_state->cpu_pages_dma_addrs[page_id]);
            UVM_ASSERT(status == NV_OK);
        }

        va_block->cpu.pages[page_id] = page;
    }

    printk(KERN_INFO "[Debug] file write complete\n");

    return status;
}
```

**Comment by msharmavikram** [comment]
If you notice, the file writes complete printk never gets called. Which means something inside the loop is causing the issue.

**Comment by pakmarkthub** [comment]
I didn't expect the console to not show anything further. Let me review the code and get back to you. This would take some time.

In the meantime, if you are ok with it, can you help narrow down to the line that causes this issue? You can use the same technique of inserting `printk` between each line and see where the issue comes from.

**Comment by msharmavikram** [comment]
Sure. I will be doing that and will keep this thread posted on what I find.

**Comment by msharmavikram** [comment]
One additional message printed - 

```
[Sep 8 22:00] nvidia-uvm: Loaded the UVM driver, major device number 235.
[Sep 8 22:03] [Debug] Write begin called
[  +0.000018] [Debug] before struct page
[  +0.000010] [Debug] inode lock captured
[  +0.000012] [Debug] file remove privs
[  +0.000013] [Debug] file update time
               [Debug] Starting Writes
[  +0.000028] [Debug] Writing pageid 0
[  +0.000012] BUG: kernel NULL pointer dereference, address: 0000000000000000
[  +0.000017] #PF: supervisor instruction fetch in kernel mode
[  +0.000014] #PF: error_code(0x0010) - not-present page
[  +0.000014] PGD 0 P4D 0 
```

**Comment by pakmarkthub** [comment]
I cannot reproduce this bug on my system. I don't have V100 but GPU may not be the root cause. I have a few questions:
1. What is your OS (Ubuntu 20.04, Centos 8, etc.)?
2. What is your file system your file is on (ext-4, etc.)?
3. Is your storage a physical one or is it through network? Do you have a hw/sw raid on top of the physical storage?
4. Can you change Linux kernel? I developed and tested DRAGON on Ubuntu with Linux 5.3.0-40. If I remember correctly, that version is based on the upstream version higher than 5.3.1, which you are using. I also test with the upstream kernel 5.4.28 with your toy example and everything works fine.

Actually, I suspect kernel 5.3.1 might require a special handle. I am installing the kernel and will test DRAGON on it.

**Comment by pakmarkthub** [comment]
DRAGON works fine with Linux kernel 5.3.1 (compiled and installed from source). A few more questions:
1. When you encounter the issue, is it kernel panic (the whole system is not responding anymore and you need to restart) or is it looks like a live/dead lock (the application freezes)?
2. Can you check if the kernel log is disabled in your system? A kernel panic message like in https://unix.stackexchange.com/questions/194171/kernel-panic-dumps-no-log-files is very useful in pinpointing the root cause. As I cannot reproduce this bug and without the kernel panic log, identifying the root cause is very hard.

**Comment by msharmavikram** [comment]
Thanks fort checking. Answering your questions in order:

1. CentOS 8 - Kernel 5.3.1 - compiled from linux-stable repo. Let me attach the.[config](https://gist.github.com/msharmavikram/ac1206ee9bb49ae065015a8da1a47dad#file-config_5-3-1) file too. (it would be great if you can share your .config file so that I can check for difference). 
2. ~~EXT4~~  XFS (check below comments)
3. physical - using a PCIe SSD
4. I can easily upgrade to 5.4.28 and will do and let you know the update. 
5. The whole system is not responding anymore and you need to hard restart from BMC. 
6. In one of the runs, I ended up with the following error - 

```
[Sep 8 22:00] nvidia-uvm: Loaded the UVM driver, major device number 235.
[Sep 8 22:03] [Debug] Write begin called
[  +0.000018] [Debug] before struct page
[  +0.000010] [Debug] inode lock captured
[  +0.000012] [Debug] file remove privs
[  +0.000013] [Debug] file update time
               [Debug] Starting Writes
[  +0.000028] [Debug] Writing pageid 0
[  +0.000012] BUG: kernel NULL pointer dereference, address: 0000000000000000
[  +0.000017] #PF: supervisor instruction fetch in kernel mode
[  +0.000014] #PF: error_code(0x0010) - not-present page
[  +0.000014] PGD 0 P4D 0 
```

**Comment by pakmarkthub** [comment]
Thank you for the `dmesg` log. I believe that the bug has something to do with missing page but the log is not verbose enough to pinpoint the root cause.

I have tried your .config file but still based on Ubuntu18.04. DRAGON works fine. I am installing CentOS8 with your config file. Hopefully, I can reproduce this bug.

About your machine, are you using multiple GPUs or only one V100? If multiple, are they connected via NVLink or PCIe?

**Comment by pakmarkthub** [comment]
I can reproduce this bug with CentOS8.2 with kernel 5.3.1 compiled using your .config. I don't know why Ubuntu18.04 (with the same kernel and config) does not have this problem. But now I have an environment for doing investigation.

**Comment by pakmarkthub** [comment]
In your toy application, you point the file path to `/home/vsm2/dragon/examples/dragon_test/data/new.mem`. Are you sure that the file system of that mount point is `ext4` and it is not `xfs`? 

By default, CentOS8 mounts your home directory under an lvm partition. The file system is `xfs` and you can check using `mount`. DRAGON uses `write_begin` which is not available in `xfs`. I plan to add support in the future but would take some time.

For now, you can create another partition that uses `ext4`. Then make sure that the file you map is in that partition.

Please let me know if that works for you.

**Comment by msharmavikram** [comment]
Thank you so much for the debug and I am glad that you are able to reproduce the bug and point me to what I was doing wrong. You rightly pointed out that the filesystem is an issue. I changed the writes to ext4 and it worked fine. Interested to note that the xfs didn't cause any issue with reads. 

Also, can we add a checker in the dragon_map to see if the FS is not ext4, then throw an error?
